### PR TITLE
proposed structure

### PR DESCRIPTION
**Pull request by Hoohm**
Hello @dbrg77,

here is the PR I had in mind (minus the whitelist).

I'm the maintainer of [CITE-seq-Count](https://github.com/Hoohm/CITE-seq-Count) and I have more and more people coming to me asking why there their data looks empty on the Feature Barcoding when using 10xV3 kit.

The main problem is that the 10x V3 kit for FB has one cell barcode for the RNA and another one for the same cell for the FB.

This leads to confusion among users. I want to automate the conversion of the cell barcodes and integrate it into the software.

I could have simply added the whitelist to the code or pulled it from cellranger but I'd rather centralize all the whitelists into one repo with one similar structure to fetch them.

This is the first raw draft of what I'm proposing here.

The main entry would be the `definitions.json` at the top level which points towards adapters, whitelist, etc... We can also add barcode positions, R1, R2 definitions, etc...

What I'm aiming towards is a repo where people using different software could pull data when they need it for their software, standardizing at the same time how you pull the data to make it easier for developers.

This structure is totally up for discussion, I just drafted this in 10min yesterday :)

Let me know what you think. Have a great day

### CODE REVIEW

**Comment by dbrg77** [comment]
Hi @Hoohm ,

Thanks for doing this. Now I understand. I agree it is convenient to have the whitelist in a centralised place.

The structure seems good to me at this moment. I'm just going to merge the PR, and I will try to add git-lfs later.

Regards,
Xi

**Comment by Hoohm** [comment]
Hey, any news regarding adding git lfs to the repo?

**Comment by dbrg77** [comment]
Hi, sorry for the very late reply. I've been away from my gmail for quite a while due to internet speed and I missed this notification. I have now installed lfs inside the repo. I think you can now try adding the barcodes and track the file.

**Comment by Hoohm** [comment]
No problem, I'm having a hard time finding bandwidth for this right now as well :(

Will keep you posted when I get back on track

**Pull request merged**
